#!/usr/bin/env bash
## Generate methscope's compiled registry from the suite's file table.
##
##   tools/make_registry.sh          write src/registry.h
##   tools/make_registry.sh --check  verify it matches the table (make test)
##
## The table is YAME/tools/registry/files.tsv, read through that directory's
## lib.sh -- the whole of what the suite's tools share. This emitter is
## methscope's and lives here, because what methscope offers is methscope's
## business: YAME's generator makes YAME's header and cannot be pointed
## elsewhere (it stopped taking --tool= at YAME c8bc8e4).
##
## Emission is offline and reads nothing but the table. Filling a blank digest
## or size is `tools/make_registry.sh --refresh` on the YAME side; this never
## touches the network.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
. "$root/YAME/tools/registry/lib.sh"

## What methscope offers, as store_path globs. `*` stops at a slash.
##   hg38/data/*          the example .cg files the docs fetch
##   {hg38,mm10}/models/* the published bundles
##   */cpg_nocontig.cr    every coordinate stream -- hg38 AND mm10 AND mm39.
##                        The mouse models need mm10's row space; mm39 has
##                        been offered since the old `coordinates` unit.
##   */*.coord.tsv.gz     every platform's per-probe genome coordinates, the
##                        table `mliftover --to <platform>` joins on
##   */*.ordering.tsv.gz  and its probe IDs in row order, which decide the
##                        probe TYPE: only cg probes are joined
PATTERNS=( 'hg38/data/*' 'hg38/models/*' 'mm10/models/*' '*/cpg_nocontig.cr'
           '*/*.coord.tsv.gz' '*/*.ordering.tsv.gz' )

emit() {
  cat <<'EOF'
/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * What `methscope fetch` knows how to download: one row per file, keyed
 * source@tag:remote_path, with where it lands, the digest it must have, its
 * size, and what to call it. Projected from the suite's file table
 * (YAME/tools/registry/files.tsv at the pinned submodule) by the globs in
 * this repo's tools/make_registry.sh, so what the binary fetches and what
 * its docs name come from one place.
 *
 * There is no directory row here -- a directory is the files whose store_path
 * sits in it -- and no anchor: each file is verified against its own digest.
 *
 * SPDX-License-Identifier: LicenseRef-CHOP-Academic-BSD-2-Clause
 * Use of this software is available to academic and non-profit institutions
 * for research purposes under the 2-Clause BSD License; for use or transfers
 * to commercial entities, inquire with Dr. Wanding Zhou at zhouw3@chop.edu.
 * See the LICENSE file at the root of the repository for the full terms.
 * Copyright (C) 2025-present The Children's Hospital of Philadelphia.
 */
#ifndef _MS_REGISTRY_H
#define _MS_REGISTRY_H

#include <stddef.h>
#include <stdint.h>

#include "assets.h"   /* yame_asset_file_t */

static const yame_asset_file_t MS_FILES[] = {
EOF
  files_of "${PATTERNS[@]}" | /usr/bin/awk -F'\t' '
    function q(s,   i, c, r) {
      r = ""
      for (i = 1; i <= length(s); i++) { c = substr(s, i, 1); if (c == "\\" || c == "\"") r = r "\\" c; else r = r c }
      return "\"" r "\""
    }
    function url(key,   src, tag, path, st) {
      path=key; sub(/^.*:/, "", path); st=key; sub(/:[^:]*$/, "", st)
      src=st; sub(/@[^@]*$/, "", src); tag=st; sub(/^.*@/, "", tag)
      if (src ~ /^hf:/) { sub(/^hf:/, "", src); return "https://huggingface.co/" src "/resolve/" tag "/" path }
      return "https://raw.githubusercontent.com/" src "/" tag "/" path
    }
    { printf "    { %s, %s, %s, %s, %s, %s, %s, %s, %s },\n",
             q($1), q($2), q(url($1)), q($3), ($4==""?0:$4), q($7), q($8), q($9), q($10) }
    END { if (NR == 0) { print "make_registry.sh: the globs matched no rows" > "/dev/stderr"; exit 1 } }'
  cat <<'EOF'
    /* the terminator: YAME_NFILES counts rows up to it. Leave it out and the
       registry silently loses its last file. */
    { NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL }
};

#define MS_FILES_N YAME_NFILES(MS_FILES)

#endif /* _MS_REGISTRY_H */
EOF
}

out=$root/src/registry.h
if [ "${1:-}" = --check ]; then
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  if cmp -s "$tmp" "$out"; then
    echo "registry is current ($(grep -c '^    { "' "$tmp") files)"
  else
    echo "src/registry.h is behind the file table: run \`make registry\`" >&2
    diff "$out" "$tmp" | head -20 >&2
    exit 1
  fi
else
  emit > "$out"
  echo "wrote $out ($(grep -c '^    { "' "$out") files)"
fi
