#!/usr/bin/env python3
"""Render every subcommand's `-h` into the Reference tab of docs/index.html.

The help text is what the binary prints, never pasted: this runs
`./methscope <sub> -h` for every subcommand the banner advertises and fills
the marker pair on the Reference tab, one card per banner SECTION (Models & data, MRMP
construction, ...) holding a folded entry per subcommand with the id
`ref-<sub>`, so an example's highlighted `methscope <sub>` can link to it
and open it. Order and grouping are the banner's own.

The binary runs under a FIXED environment (HOME=/home/user, no store
variables), because `fetch -h` prints the resolved store path and the page
must not depend on whose machine built it.

    docs/build_help.py            rewrite docs/index.html in place
    docs/build_help.py --check    exit 1 if the page is behind the binary

`make docs` runs it; `make test` runs --check -- so the page can never show
help the binary does not print.
"""
import html, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")
MS = os.path.join(ROOT, "methscope")
BEGIN, END = "<!-- help:begin (generated by docs/build_help.py from `methscope <sub> -h`) -->", "<!-- help:end -->"
## The banner parse and the -h dump live in docs/helpdump.py, shared with
## make_llms.py: two references built from two collections could disagree, and
## on 2026-09-17 they did (the page rendered all seventeen subcommands, llms.txt
## four, and where they overlapped they had drifted apart).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from helpdump import banner_sections as _banner_sections, help_of   # noqa: E402

def banner_sections():
    return _banner_sections(MS)

def entry(name, desc):
    """One folded entry; a link to #ref-<name> opens it (the page's hash router)."""
    body = help_of(MS, name, "-h")
    return ('  <details class="ref" id="ref-%s">\n    <summary><code class="inl">methscope %s</code>'
            ' <span class="m">— %s</span></summary>\n'
            '    <pre class="help"><code>%s</code></pre>\n  </details>'
            % (name, name, html.escape(desc, quote=False), html.escape(body, quote=False)))

def build():
    """One card per banner section, its subcommands folded inside, in banner order."""
    out, n = [BEGIN], 0
    for heading, cmds in banner_sections():
        title, _, note = heading.partition(" — ")
        h2 = html.escape(title, quote=False) + (' <span class="m">— %s</span>' % html.escape(note, quote=False) if note else "")
        out.append('<section class="card">\n  <h2>%s</h2>' % h2)
        for name, desc in cmds:
            out.append(entry(name, desc)); n += 1
        out.append('</section>')
    out.append(END)
    return "\n".join(out), n

def main():
    page = open(PAGE, encoding="utf-8").read()
    i, j = page.find(BEGIN), page.find(END)
    if i < 0 or j < 0: sys.exit("build_help.py: markers not found in docs/index.html")
    block, n = build()
    new = page[:i] + block + page[j + len(END):]
    if "--check" in sys.argv:
        if new != page: sys.exit("docs/index.html reference is behind the binary's -h: run `make docs`")
        print("reference is current (%d subcommands)" % n); return
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new); print("rendered %d subcommand references into docs/index.html" % n)
    else:
        print("reference unchanged")

if __name__ == "__main__": main()
