#!/usr/bin/env python3
"""Regenerate the published-models entries on the Models tab of docs/index.html.

A model is described ONCE, in YAME's data/assets.tsv (key = the filename
before the first dot), compiled into every tool as assetinfo.h. This reads the
SUBMODULE's copy at the pinned tag -- never a sibling checkout -- so the page
describes exactly what the binary carries and fetches, and rewrites the table
between the two markers below. What is not in the TSV (tag, size, which
directory) comes from the compiled registry, through `methscope fetch -l`.

    docs/build_models.py            rewrite docs/index.html in place
    docs/build_models.py --check    exit 1 if the committed page is behind

Run from the repo root, after `make` (it needs ./methscope). `make docs` and
`make test` call it.
"""
import html, os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TSV  = os.path.join(ROOT, "YAME", "data", "assets.tsv")
PAGE = os.path.join(ROOT, "docs", "index.html")
MS   = os.path.join(ROOT, "methscope")
BEGIN, END = "<!-- models:begin (generated by docs/build_models.py; edit YAME/data/assets.tsv) -->", "<!-- models:end -->"
## The Bank-classifiers table and the sentence beside the Classify example say
## the same three numbers as the cards, and used to say them by hand: at 0.10
## both still carried the v9 lites (233 sets / 208 resolvers / 51 MB against the
## shipped 178 / 150 / 21 MB) while the cards below were right. One source now.
BANK_BEGIN = "<!-- bank:begin (generated by docs/build_models.py; edit YAME/data/assets.tsv) -->"
BANK_END   = "<!-- bank:end -->"

## the order the table is read in: classifiers, references, decoders; within
## a group the newest recipe first, so the model for new work is the first row
ROLE = {".clfx": (0, "classifier"), ".msdref": (1, "deconvolution reference"),
        ".updecx": (2, "upscale decoder")}

def read_tsv(path):
    rows = {}
    with open(path, encoding="utf-8") as f:
        cols = None
        for line in f:
            if line.startswith("#") or not line.strip(): continue
            parts = line.rstrip("\n").split("\t")
            if cols is None: cols = parts; continue
            rows[parts[0]] = dict(zip(cols, parts))
    return rows

def registry_models():
    """(dir, file, tag, bytes) for every file under a */models directory, from
    the compiled registry. An empty private store keeps the state column
    quiet; nothing is downloaded."""
    with tempfile.TemporaryDirectory() as d:
        env = dict(os.environ, METHSCOPE_DATA_HOME=d)
        out = subprocess.run([MS, "fetch", "-l"], env=env, capture_output=True,
                             text=True, check=True).stdout
    for line in out.splitlines()[1:]:
        t = line.split("\t")
        if t[0].endswith("/models"):
            yield t[0], t[4], t[2], int(t[5])

def human(b):
    """Binary units, LABELLED binary. This divided by 1024 and wrote "MB", so a
    29,075,778-byte file read as "28 MB" on the page beside a row whose prose
    said 29 MB (decimal) and a disk that shows 27.7 MiB -- one file, three
    numbers, reported 2026-09-17. `fetch` reports binary too, so the unit is
    right and only the label was wrong."""
    for u in ("B", "KiB", "MiB", "GiB"):
        if b < 1024 or u == "GiB":
            return ("%.0f %s" if u != "GiB" else "%.1f %s") % (b, u)
        b /= 1024.0

N = r"[0-9.]+(?: \+/- [0-9.]+)?"           # a number, optionally with its +/- spread
ACC = re.compile(r"(class-balanced %s[ /,]+micro %s|micro %s[ /,]+class-balanced %s"
                 r"|accuracy [0-9.]+|about [0-9.]+%% on an independent cohort)" % (N, N, N, N), re.I)

def accuracy(row):
    """The first accuracy statement in processing, else biology -- the rows put
    it in a fixed shape, so a regex finds it. '—' is an honest gap."""
    for col in ("processing", "biology"):
        m = ACC.search(row.get(col, ""))
        if m: return m.group(1)
    return "—"

ROLE_TITLE = {0: ("Classifiers", "<code class=\"inl\">.clfx</code> — run with <code class=\"inl\">classify</code>"),
              1: ("Deconvolution references", "<code class=\"inl\">.msdref</code> — run with <code class=\"inl\">deconv</code>"),
              2: ("Upscale decoders", "<code class=\"inl\">.updecx</code> — run with <code class=\"inl\">upscale</code>")}

def para(label, text):
    return "    <p><b>%s.</b> %s</p>" % (label, html.escape(text, quote=False)) if text and text != "?" else ""

def entry(d, f, tag, size, r):
    """One folded entry per file; prose, not code. A link to #model-<key> opens it."""
    key = f.split(".", 1)[0]
    title = r.get("title") or "—"
    acc = accuracy(r)
    body = [para("What it is", r.get("biology", "")),
            "    <p><b>Accuracy.</b> %s</p>" % html.escape(acc, quote=False) if acc != "—" else "",
            para("How it was built", r.get("processing", "")),
            para("Source", r.get("source", "")), para("Citation", r.get("citation", "")),
            "    <p class=\"m\">%s · tag %s · %s</p>" % (html.escape(d), html.escape(tag), human(size))]
    return ('  <details class="model" id="model-%s">\n    <summary><code class="inl">%s</code> '
            '<span class="m">— %s · %s</span></summary>\n%s\n  </details>'
            % (key, html.escape(f), html.escape(title, quote=False), human(size), "\n".join(b for b in body if b)))

def build():
    tsv = read_tsv(TSV)
    items = []
    for d, f, tag, size in registry_models():
        key, ext = f.split(".", 1)[0], "." + f.rsplit(".", 1)[1]
        items.append((ROLE.get(ext, (9, ext))[0], d, f, tag, size, tsv.get(key, {})))
    items.sort(key=lambda x: (x[0], x[1], x[2]))
    out, role = [BEGIN], None
    for r0, d, f, tag, size, r in items:
        if r0 != role:
            if role is not None: out.append("</section>")
            t, m = ROLE_TITLE.get(r0, (r0, ""))
            out.append('<section class="card">\n  <h2>%s <span class="m">— %s</span></h2>' % (t, m))
            role = r0
        out.append(entry(d, f, tag, size, r))
    out.append("</section>")
    out.append('<section class="card">\n  <p class="m">Generated from YAME\'s <code class="inl">data/assets.tsv</code> at the '
               'submodule\'s tag by <code class="inl">docs/build_models.py</code>; the same rows describe '
               'each file in <code class="inl">methscope fetch</code>. Edit the TSV, not this page.</p>\n</section>')
    out.append(END)
    return "\n".join(out)

def bank_table(rows, size_of):
    """The four bank classifiers, from their assets.tsv rows.

    A _full row states both counts ("1,981 sets, 1,953 resolvers"); a _lite row
    states only its resolvers ("the 150 class pairs with the thinnest ..."). The
    difference between a full's two numbers IS its hard-block count, and a lite
    keeps the same hard blocks -- that is what "one flag apart" means -- so the
    lite's set count is resolvers + hard blocks. Checked against `inspect`:
    human 1,981-1,953 = 28 -> 150+28 = 178; mouse 837-820 = 17 -> 100+17 = 117.
    """
    import re
    pair  = re.compile(r"\(([\d,]+) sets, ([\d,]+) resolvers\)")
    lite  = re.compile(r"resolver for the ([\d,]+) class pairs")
    num   = lambda t: int(t.replace(",", ""))
    out, blocks = [], {}
    for key in ("hg38_celltype_full", "hg38_celltype_lite",
                "mm10_brain_full", "mm10_brain_lite"):
        row = rows.get(key)
        if not row: continue
        bio, species = row.get("biology", ""), key.split("_")[0]
        m = pair.search(bio)
        if m:
            sets, res = num(m.group(1)), num(m.group(2))
            blocks[species] = sets - res
            note = "every class pair"
        else:
            m = lite.search(bio)
            if not m:
                sys.exit("build_models.py: %s states neither a (sets, resolvers) "
                         "pair nor a resolver count; fix its assets.tsv row" % key)
            res = num(m.group(1))
            if species not in blocks:
                sys.exit("build_models.py: %s comes before its _full row" % key)
            sets = res + blocks[species]
            note = "the thinnest-footprint pairs"
        out.append("    <tr><td><code>%s.clfx</code></td><td>%s</td>"
                   "<td>%s &mdash; %s</td><td>%s</td></tr>"
                   % (key, format(sets, ","), format(res, ","), note,
                      size_of("%s.clfx" % key)))
    return "\n".join(out)

def main():
    page = open(PAGE, encoding="utf-8").read()
    i, j = page.find(BEGIN), page.find(END)
    if i < 0 or j < 0: sys.exit("build_models.py: markers not found in docs/index.html")
    new = page[:i] + build() + page[j + len(END):]

    ## the bank table and the one sentence that repeats its lite size
    rows = read_tsv(TSV)
    sizes = {f: b for _, f, _, b in registry_models()}
    size_of = lambda f: human(sizes[f]) if f in sizes else "\u2014"
    bi, bj = new.find(BANK_BEGIN), new.find(BANK_END)
    if bi < 0 or bj < 0:
        sys.exit("build_models.py: bank markers not found in docs/index.html")
    block = ("%s\n  <table>\n"
             "    <tr><th></th><th>sets</th><th>resolvers</th><th>size</th></tr>\n"
             "%s\n  </table>\n"
             "  <p class=\"m\">Sizes are the catalogue's; sets and resolvers come from each "
             "model's row in YAME's <code>assets.tsv</code>, the same rows the cards below "
             "use, so the two cannot disagree.</p>\n  %s"
             % (BANK_BEGIN, bank_table(rows, size_of), BANK_END))
    new = new[:bi] + block + new[bj + len(BANK_END):]
    if "--check" in sys.argv:
        if new != page:
            sys.exit("docs/index.html model table is behind YAME/data/assets.tsv: run `make docs`")
        print("model table is current"); return
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new); print("rewrote the model table in docs/index.html")
    else:
        print("model table unchanged")

if __name__ == "__main__": main()
