#!/usr/bin/env python3
"""Render every subcommand's `-h` into the Reference tab of docs/index.html.

The help text is what the binary prints, never pasted: this runs
`./methscope <sub> -h` for every subcommand the banner advertises and fills
the marker pair on the Reference tab, one card per banner SECTION (Models & data, MRMP
construction, ...) holding a folded entry per subcommand with the id
`ref-<sub>`, so an example's highlighted `methscope <sub>` can link to it
and open it. Order and grouping are the banner's own.

The binary runs under a FIXED environment (HOME=/home/user, no store
variables), because `fetch -h` prints the resolved store path and the page
must not depend on whose machine built it.

    docs/build_help.py            rewrite docs/index.html in place
    docs/build_help.py --check    exit 1 if the page is behind the binary

`make docs` runs it; `make test` runs --check -- so the page can never show
help the binary does not print.
"""
import html, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")
MS = os.path.join(ROOT, "methscope")
BEGIN, END = "<!-- help:begin (generated by docs/build_help.py from `methscope <sub> -h`) -->", "<!-- help:end -->"
ENV = {"HOME": "/home/user", "PATH": os.environ.get("PATH", ""), "LC_ALL": "C", "TERM": "dumb"}

def banner_sections():
    """The bare banner, section by section: a heading is a line with no leading
    space that is followed by command lines; a command line is two leading
    spaces, the name, spaces, a capitalised description (the parse
    test/t_usage.sh uses). Returns [(heading, [(name, description), ...])]."""
    out = subprocess.run([MS], env=ENV, capture_output=True, text=True).stderr
    sections, heading = [], None
    for line in out.splitlines():
        m = re.match(r"^  ([a-z][a-z0-9-]+) +([A-Z].*)$", line)
        if m and heading is not None:
            sections[-1][1].append((m.group(1), m.group(2).strip()))
        elif line and not line.startswith(" ") and not line.startswith("Usage") and not line.startswith("Run "):
            heading = re.sub(r"\x1b\[[0-9;]*m", "", line).strip()
            sections.append((heading, []))
    return [(h, cmds) for h, cmds in sections if cmds]

def entry(name, desc):
    """One folded entry; a link to #ref-<name> opens it (the page's hash router)."""
    text = subprocess.run([MS, name, "-h"], env=ENV, capture_output=True, text=True)
    body = (text.stdout or text.stderr).rstrip("\n")
    return ('  <details class="ref" id="ref-%s">\n    <summary><code class="inl">methscope %s</code>'
            ' <span class="m">— %s</span></summary>\n'
            '    <pre class="help"><code>%s</code></pre>\n  </details>'
            % (name, name, html.escape(desc, quote=False), html.escape(body, quote=False)))

def build():
    """One card per banner section, its subcommands folded inside, in banner order."""
    out, n = [BEGIN], 0
    for heading, cmds in banner_sections():
        title, _, note = heading.partition(" — ")
        h2 = html.escape(title, quote=False) + (' <span class="m">— %s</span>' % html.escape(note, quote=False) if note else "")
        out.append('<section class="card">\n  <h2>%s</h2>' % h2)
        for name, desc in cmds:
            out.append(entry(name, desc)); n += 1
        out.append('</section>')
    out.append(END)
    return "\n".join(out), n

def main():
    page = open(PAGE, encoding="utf-8").read()
    i, j = page.find(BEGIN), page.find(END)
    if i < 0 or j < 0: sys.exit("build_help.py: markers not found in docs/index.html")
    block, n = build()
    new = page[:i] + block + page[j + len(END):]
    if "--check" in sys.argv:
        if new != page: sys.exit("docs/index.html reference is behind the binary's -h: run `make docs`")
        print("reference is current (%d subcommands)" % n); return
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new); print("rendered %d subcommand references into docs/index.html" % n)
    else:
        print("reference unchanged")

if __name__ == "__main__": main()
