#!/usr/bin/env python3
"""Capture `methscope inspect` output for every published model.

Writes docs/inspect_snapshots.txt, which docs/build_models.py renders into the
Models tab. This is the ONLY step that needs the model files, and they are
14 GB -- so it is deliberately not part of `make docs` or `make test`. Those
read the committed snapshot instead, which is what keeps the suite offline and
runnable in a conda build. The trade is the same one the Models tab already
makes with assets.tsv: the page is generated from a checked-in file, and the
file is refreshed by hand when the artifacts change.

    docs/capture_inspect.py <dir>          capture from a directory of models
    docs/capture_inspect.py <dir> --check  exit 1 if the snapshot is behind

Run it after a model tag, from wherever the artifacts live:

    docs/capture_inspect.py /mnt/isilon/zhou_lab/projects/20260726_HuggingFace_Models_git

The file records the binary that produced it, because inspect's output is
version-dependent -- a snapshot taken by an older methscope would silently
describe an older reading of the same bytes.
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MS   = os.path.join(ROOT, "methscope")
SNAP = os.path.join(ROOT, "docs", "inspect_snapshots.txt")
EXT  = (".clfx", ".msdref", ".updecx")
MAXLINES = 60          # a deep .clfx node table runs long; the page scrolls


def capture(d):
    files = sorted(f for f in os.listdir(d) if f.endswith(EXT))
    if not files:
        sys.exit("no model files (%s) under %s" % ("/".join(EXT), d))
    ver = subprocess.run([MS, "--version"], capture_output=True, text=True,
                         check=True).stdout.strip()
    out = ["# generated by docs/capture_inspect.py -- do not edit by hand",
           "# " + ver, ""]
    for f in files:
        r = subprocess.run([MS, "inspect", os.path.join(d, f)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("inspect failed on %s:\n%s" % (f, r.stderr.strip()))
        lines = [l.rstrip() for l in r.stdout.splitlines()]
        while lines and not lines[0]:
            lines.pop(0)
        while lines and not lines[-1]:
            lines.pop()
        if len(lines) > MAXLINES:
            lines = lines[:MAXLINES] + ["... (%d more lines)" % (len(lines) - MAXLINES)]
        ## The absolute path of the capture host is not interesting and would
        ## churn the file whenever the models move; the basename is.
        lines = [l.replace(os.path.join(d, f), f) for l in lines]
        out.append("=== " + f)
        out += lines
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    if len(args) != 1:
        sys.exit(__doc__)
    text = capture(args[0])
    if check:
        have = open(SNAP, encoding="utf-8").read() if os.path.exists(SNAP) else ""
        if have != text:
            sys.exit("docs/inspect_snapshots.txt is behind the models; "
                     "rerun docs/capture_inspect.py %s" % args[0])
        print("inspect snapshots are current (%d models)" % text.count("\n=== "))
        return
    open(SNAP, "w", encoding="utf-8").write(text)
    print("wrote %s (%d models)" % (SNAP, text.count("=== ")))


if __name__ == "__main__":
    main()
