#!/usr/bin/env python3
"""Refresh the subcommand help notes in index.html from the binary itself.

The hover note on a subcommand is its real `-h` output, so it cannot drift from
what the tool prints. Re-run after changing any usage string:

    ./docs/sync_help.py ./methscope

It rewrites only the block between the HELP markers; everything else is left
byte-for-byte alone.
"""
import html
import re
import subprocess
import sys
from pathlib import Path

BEGIN = "<!-- HELP:BEGIN (generated by docs/sync_help.py) -->"
END = "<!-- HELP:END -->"


def help_text(binary, cmd):
    p = subprocess.run([binary, cmd, "-h"], capture_output=True, text=True)
    out = (p.stdout + p.stderr).replace("\r", "").strip("\n")
    out = re.sub(r"\x1b\[[0-9;]*m", "", out)          # the help renderer is ANSI on a TTY
    return "\n".join(line.rstrip() for line in out.split("\n"))


def main():
    binary = sys.argv[1] if len(sys.argv) > 1 else "./methscope"
    page = Path(__file__).with_name("index.html")
    s = page.read_text()
    cmds = sorted(set(re.findall(r'data-tip="cmd-([\w-]+)"', s)))

    blocks = []
    for c in cmds:
        txt = html.escape(help_text(binary, c))
        blocks.append(
            '      <span class="tipbox" data-tip="cmd-%s">\n'
            '        <b>methscope %s</b>\n'
            '<pre class="tsch">%s</pre>\n'
            "      </span>\n" % (c, c, txt)
        )
    body = BEGIN + "\n" + "".join(blocks) + "    " + END
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), body, s, flags=re.S)
    else:
        raise SystemExit("HELP markers not found in index.html")
    page.write_text(s)
    print("synced help for %d subcommands" % len(cmds))


if __name__ == "__main__":
    main()
