/* registry.h -- GENERATED by tools/make_registry.sh --tool=methscope. Do not edit.
 *
 * What `methscope fetch` knows how to download, and the digest each directory's
 * manifest must have. One row per fetchable directory.
 *
 * store_sub is the browser path: what the tree shows under a name is what
 * lands under that name in the store, so `hg38/data` in the browser is
 * <root>/hg38/data on disk. Which upstream repo filled a directory is in
 * `source`, not in the path.
 *
 * The anchor is sha256(SHA256SUMS) at the pinned tag, hashed from the copy
 * cached under tools/registry/sums/. Verifying a fetched manifest against it
 * is what makes every per-file digest trustworthy, and comparing a STORED
 * manifest against it is how a directory says which tag filled it.
 *
 * `prior` is the same hash for every EARLIER tag still cached in the repo.
 * Without it a store one tag behind is indistinguishable from a store some
 * other tool filled, and both need -f; with it, catching up is just a fetch.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2021-present Wanding Zhou
 */
#ifndef _YAME_REGISTRY_H
#define _YAME_REGISTRY_H

#include <stddef.h>
#include <stdint.h>

#include "assets.h"   /* yame_pin_prior_t, yame_asset_file_t, yame_asset_reg_t */

/* yame_asset_file_t and yame_asset_reg_t -- the row types this table is made
 * of -- are declared in assets.h, not here: library code takes ANY tool's
 * registry as an argument, so the types cannot live in one tool's generated
 * file. This header is only the data. */

static const yame_asset_file_t YAME_FILES_coordinates_hg38[] = {
    { "cpg_nocontig.cr", "83cc96061b61ad3f7a83097705708b898b749ff0d00f9790b1f91a236a1298cd", 30318472, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_coordinates_mm10[] = {
    { "cpg_nocontig.cr", "bef068ffeb6293acf16449f986df89005b0dfc2f0cec8fae53fd57cbd8fc8224", 23825886, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_coordinates_mm39[] = {
    { "cpg_nocontig.cr", "67b183a53a820a13303a4e793465d8012b106baed0f0098bf480f623b4bfe75d", 23857084, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_hg38_data[] = {
    { "human_hg38_40_celltypes_chr20.cg", "259b05d9a0708727a800817566a6c8f165a1210f45a9ffae692a8cdcbfe08f2e", 41377893, NULL },
    { "human_hg38_40_celltypes_chr20.cg.idx", "e17bb044c67853f8954caaf1c6b77bf4ae1a7f7efb05280df796581ab1a0bca7", 2182, NULL },
    { "human_hg38_celltypes.cg", "705973c8cdd475dbee6947952bff38fe4dea7fb44dc400c33fa9df4a0bc29a96", 6402003, NULL },
    { "human_hg38_celltypes.cg.idx", "ca868d49a73c7adf650bd6d58dbe3bb7e37f1472eef9b125fa195fd7ac69bb02", 96, NULL },
    { "human_hg38_immune_mixture.cg", "bd00ecb91f472876dca82d6ae6ff880d8d29c7eee40aaa2fddea63dd03253613", 12550753, NULL },
    { "human_hg38_immune_mixture.cg.idx", "f244f1a475fc2ff42a4af6519474943331686523c33bb6aebfdb14e9e0ad00b3", 313, NULL },
    { "human_hg38_test.cg", "276fce3f98a2de653009a2cb489e5f9ea699234a1b72aecd1ea3ba03795554a6", 103698, NULL },
    { "human_hg38_test.truth.cg", "63dd50e9b86b8abcb4c70c4927fd766026aa29999268f407187c16acfb7f6f6f", 1944547, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_models_hg38_models[] = {
    { "hg38_10k1.updecx", "8f7f2d6d42f64daaba5bf9cede5146fa52c0f62b5c76b3d5c6680c5c7554b1b7", 29075778, NULL },
    { "hg38_wg.updecx", "a1aeaf7d62ec8546bd40963f2fe18dcb0bdb54360b64748c10fbd304816442d8", 2866632834, NULL },
    { "hg38_celltype_full.clfx", "4989d8178327e9a961a1834f53f68dd0e2ca7ce151959647fcbdc730d8e083ba", 161323256, NULL },
    { "hg38_celltype_lite.clfx", "a89214fe1a9a3a562eefeb2044eceac0509146df93296db3663abd5ca337b988", 22205304, NULL },
    { "hg38_sex.clfx", "3d1618f6ca24d9a9d5b0fe1806673540515e5f6e7d7950e7c8873a85bb5c742b", 30931, NULL },
    { "hg38_33celltypes.msdref", "1e299d064423e4562e012b7ad92e9536e28010691cc37ec4a9ae4ed81f7c26ff", 554067669, NULL },
    { "hg38_62celltypes.msdref", "c9c862a9de3da3820e78df73a98ffcae6c85f4f4f6e5e378c4393ac649249e56", 1510181179, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_asset_file_t YAME_FILES_methscope_models_mm10_models[] = {
    { "mm10_wg.updecx", "f25cc5317a892105a121300fef009e29e96677f9a43fd02c3b47a59bf64cd482", 2057125237, NULL },
    { "mm10_brain_full.clfx", "02e60d0ee29362ee0fc4f6a93f6122445658af77d153c0614fb4584dc81ef9c1", 67613805, NULL },
    { "mm10_brain_lite.clfx", "58df24503facfdb7a65d8862918b4f553e359ceb4191b4e2fd395c719c125047", 13917982, NULL },
    { "mm10_41celltypes.msdref", "04ebd2341d48507f6ae271fc51464116efec72c786a243eba5682fc7b0da68a6", 581825095, NULL },
    { NULL, NULL, 0, NULL }
};

static const yame_pin_prior_t YAME_PRIOR_methscope_hg38_data[] = {
    { "v3", "150e6ae8b929e59e5b49cec241683abe6e20614bc2d29bc00f083ee01da7e19b" },
};

static const yame_pin_prior_t YAME_PRIOR_methscope_models_hg38_models[] = {
    { "v1", "6d1c5db5a545ffef909b734a9e9eeb1fed3922630aa0e026e063c8969ae32de5" },
    { "v10", "312398ef131cc7686e013a8659207cccc641d007aae5965c947b15a00f095337" },
    { "v2", "219d549b9020bb418199bb7f3c4884798bf68c65f82659495493c2fff8ade6e7" },
    { "v3", "88a4933866332ff63d95b08457fcb2ca772a6302e172b7f8c681c25ed8be0b6d" },
    { "v4", "d605a8265c107c5a5aa0d005eed32955b5ddeff54cfa55359fd952a52abb5dad" },
    { "v5", "3e1a6a51226e80c696c4149f620030a83d3cd6ac96bc74a74a95852b68180eb0" },
    { "v6", "ad2cfa7d9d467d0900b81d27fc9d555c5863bb2b4ed16851f3ba23b8d4351180" },
    { "v7", "188fa1daac6b0068ae4a71b366b51a6c3c1c39129cdfb9b9cff9637105e347c9" },
    { "v8", "27a6275afab23c6777fbf3cb85bbdf39beeb70d6f35cdf25777c12491bba73a7" },
    { "v9", "df7bddc75d685dc55d70f8aebf2cfd431adf016ab005a5ea9020626a363175b6" },
};

static const yame_pin_prior_t YAME_PRIOR_methscope_models_mm10_models[] = {
    { "v1", "6d1c5db5a545ffef909b734a9e9eeb1fed3922630aa0e026e063c8969ae32de5" },
    { "v10", "312398ef131cc7686e013a8659207cccc641d007aae5965c947b15a00f095337" },
    { "v2", "219d549b9020bb418199bb7f3c4884798bf68c65f82659495493c2fff8ade6e7" },
    { "v3", "88a4933866332ff63d95b08457fcb2ca772a6302e172b7f8c681c25ed8be0b6d" },
    { "v4", "d605a8265c107c5a5aa0d005eed32955b5ddeff54cfa55359fd952a52abb5dad" },
    { "v5", "3e1a6a51226e80c696c4149f620030a83d3cd6ac96bc74a74a95852b68180eb0" },
    { "v6", "ad2cfa7d9d467d0900b81d27fc9d555c5863bb2b4ed16851f3ba23b8d4351180" },
    { "v7", "188fa1daac6b0068ae4a71b366b51a6c3c1c39129cdfb9b9cff9637105e347c9" },
    { "v8", "27a6275afab23c6777fbf3cb85bbdf39beeb70d6f35cdf25777c12491bba73a7" },
    { "v9", "df7bddc75d685dc55d70f8aebf2cfd431adf016ab005a5ea9020626a363175b6" },
};

static const yame_asset_reg_t YAME_ASSETS[] = {
    { "KYCGKB", "hg38", "https://github.com/zhou-lab/KYCGKB_hg38/raw", "v2", "", "hg38", "8e0594ade2936a7b837306cec8e4d29bb9028a6a3be5b2cdbd372af7c16f650a", YAME_FILES_coordinates_hg38, YAME_NFILES(YAME_FILES_coordinates_hg38), NULL, 0 },
    { "KYCGKB", "mm10", "https://github.com/zhou-lab/KYCGKB_mm10/raw", "v2", "", "mm10", "fbb75f8198a731f3ea2de7d2fb65e92c84f4e0f0e2ff335b9ff2e2000606f289", YAME_FILES_coordinates_mm10, YAME_NFILES(YAME_FILES_coordinates_mm10), NULL, 0 },
    { "KYCGKB", "mm39", "https://github.com/zhou-lab/KYCGKB_mm39/raw", "v2", "", "mm39", "0dfa2114daa79c8c5fabae2d4795d250266d48f7e941fd99e81cf459e72ead64", YAME_FILES_coordinates_mm39, YAME_NFILES(YAME_FILES_coordinates_mm39), NULL, 0 },
    { "methscope", "hg38/data", "https://raw.githubusercontent.com/zhou-lab/methscope_data", "v4", "test", "hg38/data", "25e22ae2c215bad9b1018da37675b7fea5b275189d8022db9d2b90fcba14290c", YAME_FILES_methscope_hg38_data, YAME_NFILES(YAME_FILES_methscope_hg38_data), YAME_PRIOR_methscope_hg38_data, YAME_NPRIOR(YAME_PRIOR_methscope_hg38_data) },
    { "methscope", "hg38/models", "https://huggingface.co/zhou-lab/methscope/resolve", "v11", "", "hg38/models", "c46daaa43888ebe9280972561c05ef8e519645806f4761f19677d46a756eb172", YAME_FILES_methscope_models_hg38_models, YAME_NFILES(YAME_FILES_methscope_models_hg38_models), YAME_PRIOR_methscope_models_hg38_models, YAME_NPRIOR(YAME_PRIOR_methscope_models_hg38_models) },
    { "methscope", "mm10/models", "https://huggingface.co/zhou-lab/methscope/resolve", "v11", "", "mm10/models", "c46daaa43888ebe9280972561c05ef8e519645806f4761f19677d46a756eb172", YAME_FILES_methscope_models_mm10_models, YAME_NFILES(YAME_FILES_methscope_models_mm10_models), YAME_PRIOR_methscope_models_mm10_models, YAME_NPRIOR(YAME_PRIOR_methscope_models_mm10_models) },
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0 }
};

#define YAME_ASSETS_N (sizeof(YAME_ASSETS)/sizeof(YAME_ASSETS[0]) - 1)

#endif /* _YAME_REGISTRY_H */
